name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

variables:
  node_version: '20.9.0'
  workingDirectory: $(Build.SourcesDirectory)/Source
  contextDirectory: Bookmon-UI/Source'

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-zealous-plant-00fa90c03-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: '$(node_version)'
    displayName: 'Install Node.js'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: $(workingDirectory)
      verbose: false
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      app_location: "/Source"
      api_location: ""
      output_location: "dist/bookmon-ui/browser"